spring:
  application:
    name: ing-user
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_ADDR:127.0.0.1:8848}
      config:
        # 默认使用的是 Nacos 上 Public 这个namespace；
        # 值是 namespace 对应的 id，id 值可以在 Nacos 的控制台获取
        namespace:
        # 默认使用的是 DEFAULT_GROUP
        group:
        server-addr: ${NACOS_DISCOVERY_ADDR:127.0.0.1:8848}
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/ing_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    database: 1
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
  profiles:
    active: dev
server:
  port: 18080
  servlet:
    context-path: /user
management:
  server:
    # Actuator Web 访问端口
    port: 18081
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
    health:
      show-detail: always
logging:
  level:
    org.springframework.security: debug
