spring:
  application:
    name: ing-user
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_DISCOVERY_ADDR:127.0.0.1:8848}
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/ing_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    database: 1
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
  profiles:
    active: dev
server:
  port: 18080
  servlet:
    context-path: /user
logging:
  level:
    org.springframework.security: debug
